### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by jgunnink** [Geopipe/BatchGeometry#1]
Hi there, are you able to provide some examples of how to use this in your readme? Thanks :+1:

**Comment by elfprince13** [comment]
Yeah - the README is definitely out of date. Assuming you're familiar with SBT (and don't need to configure a huge job with Spark to process tons of files), the main class to execute is com.geopipe.modeltools.BatchGeometry.scala. The first argument on the command line is a pattern matching the files you want to process, and the following two arguments are suffixes to be appended to the output models and output JSON batch tables, respectively.

i.e., your arguments should be something like `input-file.dae -batched.dae -batchtable.json`. You'll also need to pass arguments to the VM to set a default Spark configuration: `-Dspark.master=local[7] -Dspark.app.name=BatchGeometry` (the number in [] can be adjusted for the number of threads you want. To process a single file, it should probably actually be 1).


Let me know if this is enough to get you started.


Also, I should note that the current implementation assumes a one-one correspondence between the indices for UV coordinates and XYZ coordinates, which was valid for our models (and probably most), but isn't sufficiently general for the COLLADA spec.

**Comment by jgunnink** [comment]
Ok, thanks for the response. We've got about 2 TB of data to process and are trying to achieve this with Go, but the Spark stuff is a bit beyond us at this point. Appreciate the response though.

**Comment by elfprince13** [comment]
Using Spark for a single multicore machine is actually pretty straightforward - SBT will download the jars for you, and you can just run a regular old Java instance with the VM arguments I suggested above.
